# Generated by Django 5.2.12 on 2026-03-28 22:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakage_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity_in_trays', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-breakage_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nip', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laying_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-laying_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('size', models.CharField(choices=[('3', '3'), ('2B', '2B'), ('2A', '2A'), ('1B', '1B'), ('1A', '1A'), ('S', 'S'), ('SS', 'SS')], max_length=4)),
                ('quantity_in_trays', models.PositiveIntegerField(default=0)),
                ('adjustment_type', models.CharField(choices=[('plus', 'Plus'), ('minus', 'Minus')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-adjustment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('size', models.CharField(choices=[('3', '3'), ('2B', '2B'), ('2A', '2A'), ('1B', '1B'), ('1A', '1A'), ('S', 'S'), ('SS', 'SS')], max_length=4)),
                ('quantity_in_trays', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('intake', 'Przyjęcie'), ('sale', 'Sprzedaż'), ('adjustment_plus', 'Korekta +'), ('adjustment_minus', 'Korekta -')], max_length=20)),
                ('reference_type', models.CharField(max_length=30)),
                ('reference_id', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Gotówka'), ('bank', 'Przelew'), ('bank_due', 'Przelew z terminem płatności')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.client')),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('3', '3'), ('2B', '2B'), ('2A', '2A'), ('1B', '1B'), ('1A', '1A'), ('S', 'S'), ('SS', 'SS')], max_length=4)),
                ('quantity_in_trays', models.PositiveIntegerField(default=0)),
                ('price_per_crate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DailyIntakeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('3', '3'), ('2B', '2B'), ('2A', '2A'), ('1B', '1B'), ('1A', '1A'), ('S', 'S'), ('SS', 'SS')], max_length=4)),
                ('quantity_in_trays', models.PositiveIntegerField(default=0)),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.dailyintake')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('intake', 'size')},
            },
        ),
    ]
